const {chromium}=require('playwright'); const path=require('path'); const fs=require('fs');
const CHROME='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const url='file://'+path.join(__dirname,'index.html');
const out=path.join(__dirname,'shots142'); fs.mkdirSync(out,{recursive:true});
let pass=0, fail=0; function ok(n,c){ if(c){pass++;console.log('  PASS',n);} else {fail++;console.log('  FAIL',n);} }
(async()=>{
  const b=await chromium.launch({executablePath:CHROME});
  const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
  await p.goto(url); await p.waitForTimeout(250);
  await p.evaluate(()=>{ const S=JSON.parse(JSON.stringify(DEF)); S.creature={body:'blob',col:'#7dff8a',eyes:'dot',extra:'none',acc:'none',name:'Garrett'}; S.flags.introDone=true; Object.keys(S.flags).forEach(k=>{if(/^seen/.test(k))S.flags[k]=true;}); delete S.flags.seen142; localStorage.setItem('bq_save_v1',JSON.stringify(S)); });
  await p.goto(url); await p.waitForTimeout(400);
  await p.evaluate(()=>{ document.getElementById('splash')?.remove(); document.getElementById('btnStart').click(); }); await p.waitForTimeout(1200);

  console.log('\nTEST 1 - badge, what\'s new, map row');
  ok('badge v1.42 · Oct 6', await p.evaluate(()=>/v1\.42 · Oct 6/.test(document.getElementById('vbadge').textContent) && VERSION==='v1.42 · Oct 6'));
  ok('what\'s new card shows once', await p.evaluate(()=>document.getElementById('modal').classList.contains('on') && /neighbors moved in/.test(document.getElementById('mbox').textContent) && S.flags.seen142===true));
  await p.screenshot({path:path.join(out,'0-whatsnew.png')});
  await p.evaluate(()=>closeModal());
  const rows=await p.evaluate(()=>townPlan().map(r=>r.name));
  console.log('   rows', rows.join(' | '));
  ok('ERRANDS & SWAPS sits right after Downtown', rows.indexOf('ERRANDS & SWAPS')===rows.indexOf('DOWNTOWN · HOME')+1);
  ok('homes rows still present', rows.filter(r=>/HOMES/.test(r)).length===3);
  ok('tab chip for ERRANDS', await p.evaluate(()=>[...document.querySelectorAll('#twTabs .twTab')].some(t=>/ERRANDS/.test(t.textContent))));

  console.log('\nTEST 2 - board: 3 errands, stable for the day');
  const bd=await p.evaluate(()=>JSON.stringify(erBoard()));
  const b1=JSON.parse(bd); console.log('   board', bd);
  ok('two fetch + one trade', b1.filter(q=>q.k==='fetch').length===2 && b1.filter(q=>q.k==='trade').length===1);
  ok('board stable on re-read', await p.evaluate(()=>JSON.stringify(erBoard()))===bd);
  ok('trade involves two different people and items', b1[2].a!==b1[2].b && b1[2].x!==b1[2].y);
  await p.evaluate(()=>townGo('er_board')); await p.waitForTimeout(150);
  ok('board screen open', await p.evaluate(()=>document.getElementById('scr-erb').classList.contains('on') && document.querySelectorAll('#erbBody .er-card').length===3));
  await p.screenshot({path:path.join(out,'1-board.png'),fullPage:false});

  console.log('\nTEST 3 - fetch: need it, buy it, deliver at the door, paid, lands in the room');
  const f=b1[0];
  await p.evaluate(id=>nbVisit(id),f.who); await p.waitForTimeout(150);
  ok('room shows the errand banner', await p.evaluate(()=>/Errand/.test(document.getElementById('nbrBody').textContent)));
  ok('no give button without the item', await p.evaluate(()=>!document.querySelector('#nbrBody button[onclick^="erGiveFetch"]')));
  await p.evaluate(it=>{ S.coins=500; S.inv[it]=1; nbrRender(); },f.item);
  ok('give button appears once you have it', await p.evaluate(()=>!!document.querySelector('#nbrBody button[onclick^="erGiveFetch"]')));
  await p.screenshot({path:path.join(out,'2-fetch-at-door.png')});
  const c0=await p.evaluate(()=>S.coins);
  await p.evaluate(()=>document.querySelector('#nbrBody button[onclick^="erGiveFetch"]').click()); await p.waitForTimeout(150);
  const r3=await p.evaluate(f=>({done:erBoard()[0].done, inv:S.inv[f.item]||0, inRoom:nbRoom(f.who).placed.some(x=>x.id===f.item&&!x.g), coins:S.coins}),f);
  ok('errand marked done', r3.done); ok('item left inventory', r3.inv===0); ok('item now in their room (theirs to keep)', r3.inRoom);
  ok('paid price + 15 coins (plus any tier bonus)', r3.coins-c0>=(await p.evaluate(it=>TOWN_BYID[it].p.c,f.item))+15);
  await p.evaluate(()=>closeModal());
  ok('Square quest mark recorded', await p.evaluate(()=>{ const m=S.wk.mark[dayKey()]||{}; return !!m.errand; }));

  console.log('\nTEST 4 - trade: three steps in order, wrong door shows nothing');
  const t=b1[2];
  await p.evaluate(id=>nbVisit(id),t.b); await p.waitForTimeout(100);
  ok('step 1 not offered at B\'s door', await p.evaluate(()=>!document.querySelector('#nbrBody button[onclick^="erTradeStep"]')));
  await p.evaluate(id=>nbVisit(id),t.a); await p.waitForTimeout(100);
  await p.evaluate(()=>document.querySelector('#nbrBody button[onclick^="erTradeStep"]').click());
  ok('carrying X after step 1', await p.evaluate(t=>S.er.carry&&S.er.carry.item===t.x&&erBoard()[2].step===1,t));
  ok('A\'s door now says go to B', await p.evaluate(()=>/carry the/.test(document.getElementById('nbrBody').textContent)));
  await p.evaluate(id=>nbVisit(id),t.b); await p.waitForTimeout(100);
  await p.screenshot({path:path.join(out,'3-trade-step2.png')});
  await p.evaluate(()=>document.querySelector('#nbrBody button[onclick^="erTradeStep"]').click());
  ok('X in B\'s room, carrying Y', await p.evaluate(t=>nbRoom(t.b).placed.some(x=>x.id===t.x)&&S.er.carry.item===t.y,t));
  await p.evaluate(id=>nbVisit(id),t.a); await p.waitForTimeout(100);
  const c1=await p.evaluate(()=>S.coins);
  await p.evaluate(()=>document.querySelector('#nbrBody button[onclick^="erTradeStep"]').click()); await p.waitForTimeout(100);
  ok('trade done, Y in A\'s room, paid', await p.evaluate(t=>erBoard()[2].done&&nbRoom(t.a).placed.some(x=>x.id===t.y)&&!S.er.carry,t) && (await p.evaluate(()=>S.coins))-c1>=40);
  await p.evaluate(()=>closeModal());

  console.log('\nTEST 5 - all three done = bonus gold once');
  const g0=await p.evaluate(()=>S.gold);
  await p.evaluate(f=>{ S.inv[f.item]=1; },b1[1]);
  await p.evaluate(id=>nbVisit(id),b1[1].who); await p.evaluate(()=>document.querySelector('#nbrBody button[onclick^="erGiveFetch"]').click()); await p.waitForTimeout(100);
  await p.evaluate(()=>closeModal());
  const g1=await p.evaluate(()=>S.gold);
  ok('bonus gold for all three (tiers may add more)', g1-g0>=1);
  ok('allDay stamped', await p.evaluate(()=>S.er.allDay===ctDay()));

  console.log('\nTEST 6 - wishlist: 3 distinct, fill = reward once, door star');
  const w=await p.evaluate(()=>{ const id='sunny'; const wl=erWishOf(id); return {id,wl,mostlyTaste:wl.filter(x=>TOWN_BYID[x].style===nbTaste(id)).length}; });
  ok('wishlist has 3 distinct items', new Set(w.wl).size===3);
  ok('two of them match their taste', w.mostlyTaste>=2);
  await p.evaluate(w=>{ w.wl.forEach(x=>S.inv[x]=(S.inv[x]||0)+1); S.home.placed=[]; nbVisit(w.id); },w);
  ok('wishlist shows in the room', await p.evaluate(()=>/wishlist/.test(document.getElementById('nbrBody').textContent)));
  const cw=await p.evaluate(()=>S.coins);
  await p.evaluate(w=>{ nbTab('give'); const used={floor:0,wall:0}; w.wl.forEach(x=>{ const z=TOWN_BYID[x].zone; nbPick(x); nbSlot(z, z==='wall'?4-used.wall++:14-used.floor++); }); },w);
  await p.waitForTimeout(700);
  ok('wishlist complete flagged', await p.evaluate(w=>!!S.er.wishDone[w.id],w));
  ok('wish reward paid (60+)', (await p.evaluate(()=>S.coins))-cw>=60);
  await p.screenshot({path:path.join(out,'4-wish-done.png')});
  await p.evaluate(()=>closeModal());
  ok('does not pay twice', await p.evaluate(w=>!erCheckWish(w.id),w));
  await p.evaluate(()=>nbBackToBuilding()); await p.waitForTimeout(100);
  ok('door star in the hallway', await p.evaluate(()=>[...document.querySelectorAll('#nbbBody .nb-door')].some(d=>/⭐/.test(d.textContent)&&/Sunny/.test(d.textContent))));

  console.log('\nTEST 7 - swap meet: judge then swap, correct call pays');
  await p.evaluate(()=>{ S.inv={stool:2,plant:1}; S.home.placed=[]; S.er.swap={day:'',offers:[]}; townGo('er_swap'); }); await p.waitForTimeout(150);
  const offs=await p.evaluate(()=>erSwaps().map(o=>({ask:o.ask,give:o.give,good:(TOWN_BYID[o.give].p.c||TOWN_BYID[o.give].p.n||TOWN_BYID[o.give].p.g*30)>(TOWN_BYID[o.ask].p.c||TOWN_BYID[o.ask].p.n||TOWN_BYID[o.ask].p.g*30)})));
  console.log('   offers', JSON.stringify(offs));
  ok('three offers', offs.length===3);
  ok('asks are things you have spare', offs.every(o=>['stool','plant'].includes(o.ask)));
  ok('no swap before calling the deal', await p.evaluate(()=>!document.querySelector('#swBody button[onclick^="swTake"]')));
  await p.screenshot({path:path.join(out,'5-swap.png')});
  const n0=await p.evaluate(()=>S.notes);
  await p.evaluate(g=>swJudge(0,g?'good':'bad'),offs[0].good);
  ok('right call pays notes', (await p.evaluate(()=>S.notes))-n0===3);
  await p.evaluate(()=>swTake(0));
  ok('swap moved items', await p.evaluate(o=>(S.inv[o.give]||0)>=1 && erSwaps()[0].taken,offs[0]));
  const n1=await p.evaluate(()=>S.notes);
  await p.evaluate(g=>swJudge(1,g?'bad':'good'),offs[1].good);
  ok('wrong call pays nothing but still shows the comparison', (await p.evaluate(()=>S.notes))===n1 && await p.evaluate(()=>/&gt;|>|</.test(document.querySelectorAll('#swBody .sw-mid')[1].textContent)));

  console.log('\nTEST 8 - persistence + clean');
  const pers=await p.evaluate(()=>{ save(); const o=JSON.parse(localStorage.getItem('bq_save_v1')); return {board:o.er.board.length, wish:Object.keys(o.er.wishDone).length, swaps:o.er.swap.offers.length}; });
  ok('errand state persists', pers.board===3&&pers.wish>=1&&pers.swaps===3);
  await p.reload(); await p.waitForTimeout(500);
  ok('board identical after reload', await p.evaluate(()=>JSON.stringify(erBoard().map(q=>q.k+(q.who||q.a)+q.done))) === JSON.stringify(JSON.parse(bd).map((q,i)=>q.k+(q.who||q.a)+true)));
  ok('zero uncaught page errors', errs.length===0); if(errs.length)console.log('   ',errs.join(' | '));
  ok('no error overlay', await p.evaluate(()=>!document.getElementById('muErr')));
  console.log('\n================  '+pass+' passed / '+fail+' failed  ================');
  await b.close(); process.exit(fail?1:0);
})().catch(e=>{ console.error(e); process.exit(1); });
